In [6]:
import numpy as np

In [7]:
data = np.loadtxt('ratings.txt', delimiter = "::",dtype = 'int') ## 구분기호
data

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       ...,
       [     6040,       562,         5, 956704746],
       [     6040,      1096,         4, 956715648],
       [     6040,      1097,         4, 956715569]])

In [8]:
#data 크기, 차원,원소개수

data.size # 4000836 원소개수
data.ndim # 2
data.shape # (1000209, 4) 크기

(1000209, 4)

In [9]:
### 1번 유저의 정보만을 출력

user1 = data[data[:,0] == 1]
user1 


array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       [        1,      3408,         4, 978300275],
       [        1,      2355,         5, 978824291],
       [        1,      1197,         3, 978302268],
       [        1,      1287,         5, 978302039],
       [        1,      2804,         5, 978300719],
       [        1,       594,         4, 978302268],
       [        1,       919,         4, 978301368],
       [        1,       595,         5, 978824268],
       [        1,       938,         4, 978301752],
       [        1,      2398,         4, 978302281],
       [        1,      2918,         4, 978302124],
       [        1,      1035,         5, 978301753],
       [        1,      2791,         4, 978302188],
       [        1,      2687,         3, 978824268],
       [        1,      2018,         4, 978301777],
       [        1,      3105,         5, 97830

In [10]:
# id 정보
user_id_num = data[:, 0]
user_id_num

array([   1,    1,    1, ..., 6040, 6040, 6040])

In [11]:
# 전체 사용자 평점 평균
user_rating = data[:, 2]
user_rating

user_rating_avg = user_rating.mean()
user_rating_avg 

3.581564453029317

In [19]:

user_1s_rating = user1[:,2]
user_1s_rating


array([5, 3, 3, 4, 5, 3, 5, 5, 4, 4, 5, 4, 4, 4, 5, 4, 3, 4, 5, 4, 3, 3,
       5, 5, 3, 5, 4, 4, 4, 3, 4, 4, 4, 4, 4, 4, 5, 5, 4, 5, 5, 5, 4, 4,
       4, 5, 5, 4, 5, 4, 4, 4, 4])

In [20]:
user_rating_avg = user_rating.mean()
user_rating_avg 

3.581564453029317