In [2]:
import pandas as pd
import numpy as np

In [3]:
arr = np.arange(2,51,2)
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50])

In [9]:
arr1 = np.zeros((4,4))
arr1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
arr2 = np.ones((10,10))
arr2

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [11]:
arr3 = np.full((7,4),4)
arr3

array([[4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4]])

In [24]:
arr = np.arange(3,101,3)
arr

#Reshape

arr_series = arr.reshape((3,11)) # 원소의 개수에 맞게
arr_series

# arr_series = pd.Series(arr)
# arr_series

array([[ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33],
       [36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66],
       [69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99]])

In [25]:
import random

In [33]:
# 1. 0~1 사이의 값을 랜덤하게 가지는 6*4 배열
arr_rand = np.random.rand(6,4)
arr_rand

array([[0.85455393, 0.41904651, 0.66232887, 0.55875851],
       [0.40151232, 0.59417531, 0.11140832, 0.72940233],
       [0.94182799, 0.14858839, 0.2123729 , 0.16466353],
       [0.76534458, 0.00259881, 0.01502444, 0.54748063],
       [0.47821307, 0.2038746 , 0.99191958, 0.70096704],
       [0.63696252, 0.80482108, 0.5065745 , 0.07935883]])

In [29]:
# 2. 1~100 사의 값을 랜덤하게 가지는 5 * 5 배열
arr_100 = np.random.randint(1,101,size = (5,5))
arr_100

array([[84, 65, 37, 57, 99],
       [43, 54, 17,  6,  1],
       [21, 54, 77, 76, 81],
       [78, 24, 56, 68, 98],
       [90, 60, 94, 83, 66]])

In [31]:
# 3.astype사용 => 2번의 배열을 실수형태의 원소를 가지는 배열로

arr_100 = arr_100.astype("float64")
arr_100

array([[84., 65., 37., 57., 99.],
       [43., 54., 17.,  6.,  1.],
       [21., 54., 77., 76., 81.],
       [78., 24., 56., 68., 98.],
       [90., 60., 94., 83., 66.]])

In [39]:
x = np.arange(10).reshape(2,5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [43]:
# 3,4,8,9를 indexing
x[:, 3:]
x[1, 1:4]


array([6, 7, 8])

In [45]:
y = np.arange(15).reshape(3,5)
y 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [58]:
# 3,8,13
y[:,3]

#5,6,7,8,9
y[1, :]

print(y[:2, 1:4])

[[1 2 3]
 [6 7 8]]


In [62]:
xy = np.arange(1,13).reshape(3,4)
xy [(xy >= 2) & (xy <= 5)]

array([2, 3, 4, 5])

In [63]:
x = np.random.randint(1,100, size = 10)
x

array([64, 95,  1, 35, 61, 22, 43, 47, 90, 39])

In [67]:
x[(x > 30 ) & (x < 70)]



array([64, 35, 61, 43, 47, 39])

In [68]:
x[(x % 2 == 1) | (x >= 60)]

array([64, 95,  1, 35, 61, 43, 47, 90, 39])

In [70]:
temp = np.array(
        [23.9, 24.4, 24.1, 25.4, 27.6, 29.7,
         26.7, 25.1, 25.0, 22.7, 21.9, 23.6, 
         24.9, 25.9, 23.8, 24.7, 25.6, 26.9, 
         28.6, 28.0, 25.1, 26.7, 28.1, 26.5, 
         26.3, 25.9, 28.4, 26.1, 27.5, 28.1, 25.8])

In [74]:
temp_above25 = temp[ temp > 25.0 ] 



array([25.4, 27.6, 29.7, 26.7, 25.1, 25.9, 25.6, 26.9, 28.6, 28. , 25.1,
       26.7, 28.1, 26.5, 26.3, 25.9, 28.4, 26.1, 27.5, 28.1, 25.8])

In [76]:
temp_above25_avg = temp.mean()

temp_above25_avg

25.90322580645161

### 정렬: Sort

In [77]:
arr = np.array([1,10,5,8,2,4,3,6,8,7,9])
arr

array([ 1, 10,  5,  8,  2,  4,  3,  6,  8,  7,  9])

In [78]:
np.sort(arr)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  8,  9, 10])

In [79]:
np.sort(arr)[::-1] # Descend order

array([10,  9,  8,  8,  7,  6,  5,  4,  3,  2,  1])

In [80]:
# Second Dimension n정렬
arr2d=np.array([[5,6,7,8],
              [4,3,2,1],
              [10,9,12,11]])

In [81]:
arr2d.shape

(3, 4)

In [85]:
# 열 정렬
np.sort(arr2d, axis = 1) 

array([[ 5,  6,  7,  8],
       [ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [86]:
# 행 정렬
np.sort(arr2d, axis = 0) 

array([[ 4,  3,  2,  1],
       [ 5,  6,  7,  8],
       [10,  9, 12, 11]])

#### y원소들의 평균,최대/최소갑,분산,중앙,표준편차

In [88]:
y = np.random.randint(100, size=(3,5))
y

array([[48, 30, 46, 43, 61],
       [27, 41, 12, 59, 93],
       [52, 25, 92, 58, 85]])

In [89]:
# 원소들의 평균
y.mean()

51.46666666666667

In [90]:
# 최대값/최솟값
y.min()
y.max()

93

In [91]:
# 분산
y.var()

548.2488888888889

In [93]:
#중앙값
np.median(y)

48.0

In [94]:
# 표준편차
y.std()

23.41471522117852