### NUMPY

In [3]:
import numpy as np

In [7]:
# Numpy (One Dimension)
arr1 = np.array([1,2,3,4,5])
arr1

# size of array
arr1.shape

(5,)

In [6]:
# Numpy (Second Dimension) (Two Pairs, List in List)

arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
# 전체 element의 count
arr1.size


5

In [11]:
# array type confirm
print(arr1.dtype)

int32


In [18]:
arr3 = np.array([[[6,1],[2,3]],[[7,2],[5,6]]])
print(arr3.dtype)

int32


In [19]:
arr3.size
arr3.shape
arr3.ndim


3

In [22]:
# if you want to set values to 0 or 1,

arr_zeros = np.zeros((3,4))
arr_zeros


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
arr_full = np.full((5,5),7)
arr_full

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [28]:
list_50 = []
for i in range(1,51):
    list_50.append(i)
    i += 1

arr_50 = np.array(list_50)
arr_50

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [32]:
arr = np.random.rand(2,3)
arr

array([[0.34966439, 0.81472749, 0.07970738],
       [0.43957919, 0.39710781, 0.69837737]])

In [34]:
arr = np.random.randint(2,10,size= (9,3))
arr = arr.astype("float64")

arr

array([[5., 4., 5.],
       [2., 7., 5.],
       [8., 8., 7.],
       [9., 4., 5.],
       [5., 6., 7.],
       [6., 3., 4.],
       [4., 4., 7.],
       [9., 4., 7.],
       [4., 8., 7.]])

In [36]:
arr + arr # Calculates by the arrays' elements

array([[10.,  8., 10.],
       [ 4., 14., 10.],
       [16., 16., 14.],
       [18.,  8., 10.],
       [10., 12., 14.],
       [12.,  6.,  8.],
       [ 8.,  8., 14.],
       [18.,  8., 14.],
       [ 8., 16., 14.]])

In [40]:
# indexing / slicing np.array
arr_1 = np.array([0,1,2,3,4,5])
arr_1

arr_1[5]

5

In [43]:
arr_2 = np.array([[0,1,2,3,4,5],[5,4,3,2,1,0]])
arr_2[0]

array([0, 1, 2, 3, 4, 5])

In [47]:
new_array = np.array([[4,5,6],[7,8,9]])
new_array[0][0]

new_array[0][2]

new_array[0]



array([4, 5, 6])

In [52]:
arr_3 = np.arange(10)
arr_3[3:8] = 12 # 12를 3:8 안에 넣어라

arr_3



array([ 0,  1,  2, 12, 12, 12, 12, 12,  8,  9])

In [66]:
arr_4 = np.arange(50).reshape(5,10) # array의 shape을 변형가능
arr_4 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [71]:
arr_4[4,8]

arr_4[2,9]

arr_4[1,2]

12

In [76]:
# Boolean

score = np.array([80,75,55,96,30])

    
score >= 80

score[score >= 80]

array([80, 96])

In [80]:
name = np.array(["영화","동원","성우","수민"])
name

bol = np.array(["False","True","False","True"])
bol

bol_a = array([False,True,False,True])


array(['False', 'True', 'False', 'True'], dtype='<U5')

In [81]:
score = np.array([[60,70],[70,70],[80,80],[90,90]])
score 

array([[60, 70],
       [70, 70],
       [80, 80],
       [90, 90]])

In [94]:
# Universally Function 수학 함수
# For instance, sum 
arr = np.random.randint(1,10,size = (2,5))
arr

print(arr.sum())
print(np.sum(arr))

# Average
print(arr.mean())



47
47
4.7


In [95]:
# 제곱근
arr1 = np.arange(1,6)
np.sqrt(arr1)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [97]:
# 절대값
arr = np.array([-1,-2,-3,-4,-5])
arr

np.abs(arr) # absolute value

array([1, 2, 3, 4, 5])